%% pRF_Nomenclature
%
% this is a list of structures and thier field names
% these conventional params are used in the following
%
% --FUNCTIONS-- (in UWToolbox/stimulus/pRF_Mapping)
% getBarSequence    :: randomly generates center position and angle of bar
%   stimulus
% getRingSequence    :: generates eccentricity of ring stimulus
% makeBarImage      :: generates a 2D image of the stimulus (drifting bar)
% makeRingImage      :: generates a 2D image of the stimulus (expanding ring)
% makeMaskImage     :: generates a 2D binary mask to mask off an aperture
%   and fixation region of the simulus
% makeScotomaImage  :: generates a 2D binary mask to remove stimulation
%   from simulated scatoma
% makeStimulusMovie :: takes in centers and angle generated from
%   getBarSequence and calls makeBarImage / makeMaskImage /
%   makeScotomaImage in order to generate a series of movie frames
% pRF_Estimate      :: estimate the pRFs and HDR
% pRF_Mapping      :: run the stimulus for fMRI recording

% ---- version history ----
% 1.0 :: 02.22.2012 :: ZRE
%     :: listed field names and purpose for display/stim structures
% 1.1 :: 02.24.2012 :: ZRE
%     :: changed stim.angsRad -> stim.motDirsRad to reflect what it really
%     is!
% 1.2 :: 03.23.2012 :: PB
%     :: added option for MultiFocal stimuli
% 06.04.2012 PB
% added blank periods in the drifting bar sequence

%% The DISPLAY sturucture

% display
%   .dist      = distance from screen (cm)
%   .width     = width of screen (cm)
% 	.fixColor  = [1x3] color of fixation cross (RGB)
% 	.bkColor   = [1x3] color of background (RGB)
% 	.gamma     = [256x1] achromatic linearization lookup table
%
% 	.screenAngle = pix2angle( display, display.resolution ); screen
%       resolution in visual angle
%
% 	.screenNum = max(Screen('Screens'));
% 	.skipChecks= 2;


%% the STIM structure

% ---- fields that control the display of the stimulus --------------------
% stim
%   .StimulusType           = DriftingBar or MultiFocal
%   .radDeg           = radius of stimulus aperture (deg)
% 	.fixMaskRadDeg    = radius of mask around fixation (deg) 
%   .scotoma
%       .flag   - toggle scotoma on/off
%       .center - [x y] center in degrees
%       .rad    - radius in degrees
% -------------------------------------------------------------------------

% ---- fields that control the atributes of the bar stimulus (or the arcs, for MultiFocal) --------------
% stim
%   .widthDeg         = width of bar stimulus (deg)
% 	.cyclePerDeg      = spatial frequency of chexer board on bar (cycle/deg)
% 	.degPerSecRange   = [ min max ] speed of bar stimulus (deg/sec)
% 	.flickerHz = 8;   = contrast reversal frequency
%   .durBlanksSec     =  durantion of blanks between bar sweeps
%   .nSweepsBetweenBlanks = number of sweeps separating two blank periods
%   .begendBlankSec = duration of blanks at beginning and end of run
% ---- fields generated by getBarSequence ---------------------------------
%   .centersDeg       = centers in deg, (0,0) is screen center (-y is up)
%   .motDirsRad       = direction of motion in radians (0 to the right, pi/2 is up)
% 	.degPerSec        = instantaneous speed at every TR (deg/sec)
%   .randAng          = whether bar direction is random or goes in 45 deg setps
%   .rotspeedDegPerSec = rotation speed of the carrier checkerboard (only 4 MF and merid)
% ---- fields for Meridians -----------------------------------------------
%   .meridianWidthRad = width of the wedge in radians
%   .meridianPhaseRad = orientation of the wedge in radians
% ---- fields generated by makeMFstimulus ---------------------------------
%         .wedgeStartDeg = start of wedge (in degree, from vertical)
%         .wedgeSizeDeg = wedge width (in degree, will draw in CW direction)
%         .ringOutDeg = outetr radius of the arc
%         .ringSizeDeg = arc width (outer - inner radius)

% -------------------------------------------------------------------------

% ---- fields that control the sequence -----------------------------------
% stim
%   .durSec           = duration of stimulus (sec)
% 	.secPerTR         = duration of TR (sec)
% 	.numTRs           = stim.durSec / stim.secPerTR;
% 	.nFrames          = ceil( stim.durSec * display.frameRate );
%   .durBlanksSec     = durantion of blanks between bar sweeps (sec)
%   .nSweepsBetweenBlanks = number of sweeps separating two blank periods
% -------------------------------------------------------------------------

% ---- fields that control miscellaneous atributes ------------------------
% stim
%   .seed             = seed for random number generator 
% -------------------------------------------------------------------------
